const mongoose = require("mongoose")
const Schema = new mongoose.Schema({
    aadharno: { type: "string" },
    academicyear: { type: "string" },
    appeared: { type: "string" },
    branchapplied: { type: "string" },
    caste: { type: "string" },
    category: { type: "string" },
    course: { type: "string" },
    dob: { type: "string" },
    entranceexam: { type: "string" },
    fatherannualincome: { type: "string" },
    fathermobile: { type: "string" },
    fathername: { type: "string" },
    fatheroccupation: { type: "string" },
    fullname: { type: "string" },
    gender: { type: "string" },
    hallticket: { type: "string", required: true },
    interboardoruniversity: { type: "string" },
    intergrade: { type: "string" },
    intergrouporbranch: { type: "string" },
    interschoolorcollegename: { type: "string" },
    interyearofpassing: { type: "string" },
    lateralentry: { type: "string" },
    mothermobile: { type: "string" },
    mothername: { type: "string" },
    nationality: { type: "string" },
    otherboardoruniversity: { type: "string" },
    othergrade: { type: "string" },
    othergrouporbranch: { type: "string" },
    otherschoolorcollegename: { type: "string" },
    otheryearofpassing: { type: "string" },
    otpmail: { type: "string" },
    otp: { type: "string" },
    parentmail: { type: "string" },
    permanenthouseno: { type: "string" },
    permanentpin: { type: "string" },
    permanentstate: { type: "string" },
    permanentstreet: { type: "string" },
    permanentvillage: { type: "string" },
    pgboardoruniversity: { type: "string" },
    pggrade: { type: "string" },
    pggrouporbranch: { type: "string" },
    pgschoolorcollegename: { type: "string" },
    pgyearofpassing: { type: "string" },
    presenthouseno: { type: "string" },
    presentpin: { type: "string" },
    presentstate: { type: "string" },
    presentstreet: { type: "string" },
    presentvillage: { type: "string" },
    quota: { type: "string" },
    rank: { type: "string" },
    religion: { type: "string" },
    rollno: { type: "string" },
    schoolorcollegename: { type: "string" },
    sscboardoruniversity: { type: "string" },
    sscgrade: { type: "string" },
    sscgrouporbranch: { type: "string" },
    sscyearofpassing: { type: "string" },
    studentblood: { type: "string" },
    studentmail: { type: "string" },
    studentmobile: { type: "string" },
    studentphoto: { type: "string" },
    ugboardoruniversity: { type: "string" },
    uggrade: { type: "string" },
    uggrouporbranch: { type: "string" },
    ugschoolorcollegename: { type: "string" },
    ugyearofpassing: { type: "string" },
    year: { type: "string" },
    approvedby: { type: "string" },

    allotmentorder: { type: Boolean },
    joiningreport: { type: Boolean },
    recieptofcert: { type: Boolean },
    hallticketcert: { type: Boolean },
    rankcard: { type: Boolean },
    sscmarksmemo: { type: Boolean },
    sixtencert: { type: Boolean },

    intermarksmemo: { type: Boolean },
    intercert: { type: Boolean },
    ugpc: { type: Boolean },
    ugcert: { type: Boolean },
    photos: { type: Boolean },
    aadharcard: { type: Boolean },
    othercert: { type: Boolean },




})

const studentdata = mongoose.model("studentdata", Schema)

module.exports = studentdata
